name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            profilePath: Assets/Settings/Build Profiles/Windows.asset
          - name: WindowsServer
            profilePath: Assets/Settings/Build Profiles/Windows Server.asset
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.name }}
          restore-keys: |
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v4
        with:
          buildProfile: ${{ matrix.profilePath }}
          unityVersion: 6000.2.15f1
          buildName: ${{ matrix.name }}

      - name: Zip Build
        run: |
          cd build
          zip -r ../${{ matrix.name }}.zip .

      - name: Generate Release Notes
        shell: bash
        run: |
          git fetch --force --tags
          CURRENT_TAG=${GITHUB_REF#refs/tags/}
          PREV_TAG=$(git describe --tags --abbrev=0 "$CURRENT_TAG^" 2>/dev/null || echo "")
          
          if [ -z "$PREV_TAG" ]; then
             LINK="https://github.com/${{ github.repository }}/commits/$CURRENT_TAG"
          else
             LINK="https://github.com/${{ github.repository }}/compare/$PREV_TAG...$CURRENT_TAG"
          fi
          
          echo "RELEASE_BODY=**Full Changelog**: $LINK" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: ${{ matrix.name }}.zip
          body: ${{ env.RELEASE_BODY }}
